version: '3'

services:
  php:
    build: ./docker
    container_name: php
    volumes:
      - /Users/hiker/Desktop/Project/Code/Apitp:/var/www/html
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /Users/hiker/Desktop/Project/Code/Apitp/docker/nginx.conf:/etc/nginx/nginx.conf
      - /Users/hiker/Desktop/Project/Code/Apitp:/var/www/html
    ports:
      - "8091:80"
    depends_on:
      - php
    networks:
      - my-network

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Api
      MYSQL_USER: hiker
      MYSQL_PASSWORD: hiker
    ports:
      - "3312:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  emqx:
    image: emqx/emqx:4.3.11
    container_name: emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8081:8081"
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: hiker
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql_data:
